import React from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Link, Route, Routes, Navigate } from 'react-router-dom';
import './styles.css';

function Landing() { return <main className="page"><nav><b>AUTOPrint</b><span><Link to="/login">Login</Link><Link className="button" to="/signup">Sign Up</Link></span></nav><section className="hero"><div><p className="eyebrow">SMART PRINT SHOP SOFTWARE</p><h1>Turn your shop into a <em>QR-powered</em> printing point.</h1><p className="lead">Customers upload documents through your shop QR code. Your connected printer receives the job and prints it locally.</p><Link className="button large" to="/signup">Start your shop →</Link></div><div className="preview"><div className="qr">▦</div><h3>Scan → Upload → Print</h3><div className="progress"><i /></div><p>Printer ready · 2 pages queued</p></div></section><section className="dark"><p className="eyebrow">HOW IT WORKS</p><h2>Simple for customers. Powerful for merchants.</h2><div className="steps"><div><b>01</b><h3>Create your shop</h3><p>Sign up, add your shop and connect the Agent.</p></div><div><b>02</b><h3>Share your QR</h3><p>Customers scan your unique shop code.</p></div><div><b>03</b><h3>Print automatically</h3><p>Track every job from your merchant dashboard.</p></div></div></section></main> }
function Auth({ signup=false }: {signup?: boolean}) { return <main className="auth"><div className="card"><Link to="/" className="brand">AUTOPrint</Link><h1>{signup ? 'Create your account' : 'Welcome back'}</h1><p>{signup ? 'Start managing your smart print shop.' : 'Sign in to your merchant dashboard.'}</p><input placeholder="Email address" type="email" defaultValue="merchant@autoprint.app" /><input placeholder="Password" type="password" defaultValue="password123" /><button className="button" onClick={() => window.location.href='/merchant/dashboard'}>{signup ? 'Create account' : 'Login'}</button><small>{signup ? 'Already have an account? ' : 'New to AutoPrint? '}<Link to={signup ? '/login' : '/signup'}>{signup ? 'Login' : 'Sign up'}</Link></small></div></main> }
function Merchant() { return <main className="merchant"><aside><b>AUTOPrint</b><small>Merchant App</small>{['Dashboard','Orders','Agent & Printer','Shop Settings','Analytics','Subscription','Account'].map((x,i)=><a className={i===0?'active':''} key={x}>{x}</a>)}</aside><section className="content"><header><div><small>MERCHANT CONTROL CENTER</small><h1>Good morning, merchant</h1></div><button onClick={() => window.location.href='/'}>Logout</button></header><div className="stats"><Stat n="128" l="Today orders" /><Stat n="₹12,480" l="Today revenue" /><Stat n="18" l="Active jobs" /><Stat n="96%" l="Success rate" /></div><div className="grid"><div className="panel"><h2>Live work queue</h2>{[['invoice-1042.pdf','Printing','blue'],['student-id.pdf','Queued','yellow'],['report-89.pdf','Failed','red']].map(x=><div className="row" key={x[0]}><span><b>{x[0]}</b><small>Canon LBP · 4 pages</small></span><label className={x[2]}>{x[1]}</label></div>)}</div><div className="panel"><h2>Agent status</h2><div className="status">Agent <b className="green">Online</b></div><div className="status">Printer <b className="green">Ready</b></div><div className="status">Last sync <b>2 sec ago</b></div><Link className="button full" to="/merchant/onboarding">Get customer QR</Link></div></div></section></main> }
function Stat({n,l}:{n:string;l:string}) { return <div className="stat"><small>{l}</small><strong>{n}</strong><span>Live data after Supabase setup</span></div> }
function App() { return <Routes><Route path="/" element={<Landing/>}/><Route path="/login" element={<Auth/>}/><Route path="/signup" element={<Auth signup/>}/><Route path="/merchant/*" element={<Merchant/>}/><Route path="*" element={<Navigate to="/"/>}/></Routes> }
createRoot(document.getElementById('root')!).render(<React.StrictMode><BrowserRouter><App/></BrowserRouter></React.StrictMode>);
